<?php

namespace PortfolioBundle\Repository;

/**
 * contact_informationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class contact_informationRepository extends \Doctrine\ORM\EntityRepository
{
}
