<?php

namespace PortfolioBundle\Repository;

/**
 * education_trainingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class education_trainingRepository extends \Doctrine\ORM\EntityRepository
{
}
