<?php

namespace PortfolioBundle\Repository;

/**
 * linguistic_knowledgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class linguistic_knowledgeRepository extends \Doctrine\ORM\EntityRepository
{
}
