<?php

namespace PortfolioBundle\Repository;

/**
 * professional_activitiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class professional_activitiesRepository extends \Doctrine\ORM\EntityRepository
{
}
